version: '3.4'

services:
  namenode:
    image: uhopper/hadoop-namenode
    hostname: namenode
    container_name: namenode
    domainname: hadoop
    networks: 
      - hadoop
    volumes:
      - namenode-vol:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=autohadoop
    env_file:
      - ./hadoop.env
    ports:
      - "50070:50070"

  datanode1:
    image: uhopper/hadoop-datanode
    hostname: datanode1
    container_name: datanode1
    domainname: hadoop
    networks: 
      - hadoop
    volumes:
      - datanode-vol:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

  resourcemanager:
    image: uhopper/hadoop-resourcemanager
    hostname: resourcemanager
    container_name: resourcemanager
    domainname: hadoop
    networks: 
      - hadoop
    env_file:
      - ./hadoop.env
    ports:
      - "8088:8088"

  nodemanager1:
    image: uhopper/hadoop-nodemanager
    hostname: nodemanager1
    container_name: nodemanager1
    domainname: hadoop
    networks: 
      - hadoop
    env_file:
      - ./hadoop.env

  spark:
    image: uhopper/hadoop-spark
    hostname: spark
    container_name: spark
    domainname: hadoop
    networks: 
      - hadoop
    env_file:
      - ./hadoop.env
    command: tail -f /var/log/dmesg
    ports:
      - "4040:4040"
      - "9000:9000"
      - "8080:8080"

volumes:
  namenode-vol: {}
  datanode-vol: {}

networks:
  hadoop: {}

