apiVersion: v1
kind: Service
metadata:
  name: {{ include "HadoopAutoProvisioner.fullname" . }}
  labels:
    {{- include "HadoopAutoProvisioner.labels" . | nindent 4 }}
spec:
  type: {{ .Values.flask.service.type }}
  ports:
    - port: {{ .Values.flask.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "HadoopAutoProvisioner.selectorLabels" . | nindent 4 }}
